### ISSUE TITLE
Clicking on suggestions doesn't work

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/react-abstract-autocomplete#11]
Should complete it just like enter/tab.

**Comment by flyYoyo** [comment]
this issue is not fixed！

**Comment by goto-bus-stop** [comment]
aw crap, I must've broke it again later. thanks for the heads up.

**Comment by tacack** [comment]
Hello,

Is this issue fixed?

REgards,
Vybhav

**Comment by pdumais** [comment]
Is there a workaround for this? this is pretty major IMO. Did you find the root cause?

**Comment by goto-bus-stop** [comment]
I agree this issue is quite major, but I only use this package in a side project that I don't have much time for these days and that has more important bugs. I won't be able to fix it soon but would be happy to take a PR!

**Comment by pdumais** [comment]
Yep. Looking into it. I was hoping you had isolated the root cause or could give me some pointers so I could move faster.

**Comment by pdumais** [comment]
https://github.com/goto-bus-stop/react-abstract-autocomplete/pull/160

**Comment by goto-bus-stop** [comment]
#160 landed in :package: 2.0.1, so this should be fixed for real now :pray: thanks @pdumais!
